import type { RoleProfile, SkillRequirement } from "./types";

function skill(
  partial: SkillRequirement,
): SkillRequirement {
  return partial;
}

export const ROLES: RoleProfile[] = [
  {
    id: "backend",
    name: "后端开发工程师",
    nameEn: "Backend Engineer",
    tagline: "服务端业务、数据一致性与稳定性",
    summary:
      "国内互联网与 ToB 企业社招中最常见的工程岗之一。JD 通常按语言栈（Java / Go / Python）拆分，强调能独立交付可上线服务，而不是只会写 CRUD。",
    typicalTitles: {
      junior: "初级后端 / 后端开发（1–3 年）",
      mid: "后端开发 / 中级后端（3–5 年）",
      senior: "高级后端 / 资深后端（5 年+）",
    },
    yearBands: { junior: [0, 2], mid: [3, 5], senior: [5, 15] },
    educationNote:
      "BOSS / 拉勾 / 猎聘上多数后端 JD 写「本科及以上，计算机相关优先」；大专若有可验证的线上项目，一线以下城市与中小团队仍常见。",
    sources: [
      "国内招聘平台（BOSS 直聘、拉勾、猎聘）Java/Go/Python 后端社招 JD 的技能清单结构",
      "LinkedIn / Indeed 同类 Backend Engineer JD 中常见的服务端、数据库与消息队列组合",
      "开源社区与工程博客中对「能独立负责一个服务」的资深后端能力描述",
    ],
    softSkills: [
      "能把模糊需求拆成接口与数据模型",
      "线上问题定位（日志、指标、复盘）",
      "跨端联调与书面同步进展",
    ],
    skills: [
      skill({
        id: "be-lang",
        name: "一门主流后端语言（Java / Go / Python）",
        aliases: ["java", "go", "golang", "python", "jdk", "jvm"],
        level: "must",
        category: "language",
        jdPattern:
          "国内中大型后端 JD 几乎都会把 Java、Go 或 Python 写成硬性语言栈，并常与对应生态并列，而不是「会任何一门语言即可」。",
        learnHint: "选定一门语言，按官方文档把语法、包管理、错误处理、并发原语过完，并能手写常见数据结构操作。",
        deliverable: "一份不含框架的命令行小工具 + 语言特性笔记（含并发/错误处理）。",
      }),
      skill({
        id: "be-fw",
        name: "主流 Web 框架（Spring Boot / Gin / FastAPI 等）",
        aliases: [
          "spring",
          "springboot",
          "spring boot",
          "spring cloud",
          "gin",
          "fastapi",
          "django",
          "flask",
          "express",
          "nestjs",
        ],
        level: "must",
        category: "framework",
        jdPattern:
          "社招 JD 通常点名具体框架，并要求能完成鉴权、参数校验、统一异常与分层，而不是只跑通 Hello World。",
        learnHint: "用目标框架搭一个带鉴权、分页、校验和分层的 REST 服务。",
        deliverable: "可本地启动的 REST 服务，含 OpenAPI/接口说明。",
      }),
      skill({
        id: "be-sql",
        name: "关系型数据库与 SQL（MySQL / PostgreSQL）",
        aliases: ["mysql", "postgresql", "postgres", "sql", "innodb"],
        level: "must",
        category: "infra",
        jdPattern:
          "后端 JD 几乎必写 MySQL 或 PostgreSQL，并常出现索引、事务、慢查询等关键词。",
        learnHint: "掌握事务隔离、索引选择、EXPLAIN，以及常见慢查询改写。",
        deliverable: "带索引设计说明的表结构 + 3 条优化前后的 SQL 对比。",
      }),
      skill({
        id: "be-redis",
        name: "缓存（Redis）",
        aliases: ["redis", "缓存"],
        level: "must",
        category: "infra",
        jdPattern:
          "国内后端 JD 把 Redis 与 MySQL 并列的频率很高，常见考点是缓存穿透/击穿/雪崩与过期策略。",
        learnHint: "实现一个读多写少接口的缓存层，并写清失效与一致性策略。",
        deliverable: "缓存设计短文 + 可演示的热点查询接口。",
      }),
      skill({
        id: "be-http",
        name: "HTTP / REST 与接口契约",
        aliases: ["http", "rest", "api", "openapi"],
        level: "must",
        category: "domain",
        jdPattern:
          "JD 和面试都默认候选人能独立定接口、处理幂等与错误码，而不是只对接现成文档。",
        learnHint: "为业务域写清资源模型、幂等与错误码表。",
        deliverable: "接口文档（路径、错误码、幂等说明）。",
      }),
      skill({
        id: "be-linux",
        name: "Linux 与 Git 基本功",
        aliases: ["linux", "git", "bash", "shell"],
        level: "must",
        category: "tool",
        jdPattern:
          "绝大多数工程岗 JD 默认 Linux 命令行与 Git 工作流；此项不过关会被视为基础不扎实。",
        learnHint: "熟练日志查看、进程/端口、权限与分支协作。",
        deliverable: "个人仓库的规范提交历史与 README。",
      }),
      skill({
        id: "be-mq",
        name: "消息队列（Kafka / RabbitMQ 等）",
        aliases: ["kafka", "rabbitmq", "rocketmq", "mq", "消息队列"],
        level: "should",
        category: "infra",
        jdPattern:
          "3 年左右后端 JD 常把消息队列列为加分或硬性项，用于解耦、削峰与异步任务。",
        learnHint: "用队列完成一个异步任务（下单后通知/对账），理解重试与死信。",
        deliverable: "带重试与死信说明的异步链路 Demo。",
      }),
      skill({
        id: "be-docker",
        name: "容器化（Docker）",
        aliases: ["docker", "compose", "容器"],
        level: "should",
        category: "infra",
        jdPattern:
          "近年 JD 普遍要求能用 Docker 交付，本地 Compose 启动已是中小团队基线。",
        learnHint: "把服务与依赖打成 Compose，做到他人一条命令启动。",
        deliverable: "Dockerfile + docker-compose.yml + 启动说明。",
      }),
      skill({
        id: "be-obs",
        name: "可观测性与性能排查",
        aliases: ["prometheus", "grafana", "elk", "skywalking", "监控", "链路追踪"],
        level: "nice",
        category: "infra",
        jdPattern:
          "高级后端 JD 与 SRE 交叉岗位常写监控、链路追踪、SLA；初级岗多为加分项。",
        learnHint: "给服务加上基础指标、结构化日志和一次压测记录。",
        deliverable: "一份含 QPS/延迟/错误率的压测与复盘笔记。",
      }),
    ],
    projectTemplates: [
      {
        title: "带缓存与异步的业务服务",
        detail:
          "选一个真实业务切片（订单、内容审核、权限），用主流框架 + MySQL + Redis，再加一条异步消息。重点不是页面，而是一致性、幂等与失败重试。",
        evidence: "仓库 + 架构说明 + 接口文档 + 一次问题复盘。",
        months: [2, 3],
      },
      {
        title: "可演示的性能优化案例",
        detail:
          "针对读多写少接口做索引与缓存优化，用压测对比优化前后。这是社招面试里很常见的「你做过什么优化」叙事。",
        evidence: "优化前后数据、EXPLAIN、结论边界（在什么量级有效）。",
        months: [1, 2],
      },
    ],
    interviewFocus: [
      "MySQL 索引与事务、Redis 使用边界",
      "接口幂等、分布式一致性的务实取舍",
      "一次线上或压测问题的排查过程",
    ],
  },
  {
    id: "frontend",
    name: "前端开发工程师",
    nameEn: "Frontend Engineer",
    tagline: "用户界面、工程化与浏览器性能",
    summary:
      "JD 已从「会切图」转向 TypeScript + 组件化 + 工程化。一线城市对 React/Vue 深度、性能与工程基建的要求明显高于只会写页面。",
    typicalTitles: {
      junior: "初级前端 / 前端开发（1–3 年）",
      mid: "中级前端 / 前端工程师（3–5 年）",
      senior: "高级前端 / 前端专家（5 年+）",
    },
    yearBands: { junior: [0, 2], mid: [3, 5], senior: [5, 15] },
    educationNote:
      "本科常见但不是唯一门槛；作品集与线上页面质量往往比学历更能决定初筛。",
    sources: [
      "BOSS / 拉勾前端 JD 中 React/Vue + TypeScript + 工程化的高频组合",
      "LinkedIn Frontend Engineer JD 对可访问性、性能与测试的常见写法",
      "前端社区对工程化、组件库与性能预算的通行实践",
    ],
    softSkills: ["设计还原与沟通", "能拆分交互状态", "对体验细节负责"],
    skills: [
      skill({
        id: "fe-htmlcss",
        name: "HTML / CSS 与响应式布局",
        aliases: ["html", "css", "sass", "less", "tailwind", "响应式"],
        level: "must",
        category: "language",
        jdPattern: "所有前端 JD 的底线能力；移动端适配与常见布局问题仍会在笔试出现。",
        learnHint: "不依赖 UI 库手写几个响应式页面，覆盖表单、列表、弹层。",
        deliverable: "2–3 个可在手机宽度使用的静态/组件页面。",
      }),
      skill({
        id: "fe-js",
        name: "JavaScript 核心",
        aliases: ["javascript", "js", "es6"],
        level: "must",
        category: "language",
        jdPattern: "JD 和面试仍会考闭包、异步、事件循环与 DOM 事件，而不是只问框架 API。",
        learnHint: "系统补齐异步、原型、模块与浏览器事件模型。",
        deliverable: "一份带小题解答的 JS 基础笔记（自己写，勿只收藏）。",
      }),
      skill({
        id: "fe-ts",
        name: "TypeScript",
        aliases: ["typescript", "ts"],
        level: "must",
        category: "language",
        jdPattern: "近两年中大型前端 JD 已把 TypeScript 写成默认要求，而非加分项。",
        learnHint: "用 TS 重写一个中等组件，覆盖联合类型、泛型与 API 类型。",
        deliverable: "全 TS 的组件库或业务模块。",
      }),
      skill({
        id: "fe-fw",
        name: "React 或 Vue（其一深入）",
        aliases: ["react", "vue", "vue3", "reactjs", "vuejs"],
        level: "must",
        category: "framework",
        jdPattern: "国内 JD 基本按 React 或 Vue 分栈；「两个都会一点」通常弱于「一个能讲透」。",
        learnHint: "深入一个框架的状态、生命周期/hooks、渲染与路由。",
        deliverable: "带路由、状态管理与列表/表单的 SPA。",
      }),
      skill({
        id: "fe-eng",
        name: "前端工程化（Vite / Webpack、包管理、Lint）",
        aliases: ["vite", "webpack", "eslint", "prettier", "pnpm", "工程化"],
        level: "should",
        category: "tool",
        jdPattern: "中级 JD 常写工程化、CI、组件化；只会 create-xxx 默认模板会被认为经验偏浅。",
        learnHint: "自己配构建、Lint、环境变量与基础 CI。",
        deliverable: "可复用的项目模板与约定说明。",
      }),
      skill({
        id: "fe-perf",
        name: "性能与网络（浏览器、缓存、Lighthouse）",
        aliases: ["performance", "lighthouse", "cdn", "浏览器", "性能优化"],
        level: "should",
        category: "domain",
        jdPattern: "高级前端 JD 与电商/资讯类岗位常写首屏、包体积、长列表性能。",
        learnHint: "对一个真实页面做一次可量化的性能优化。",
        deliverable: "优化前后 Lighthouse/包体积对比与取舍说明。",
      }),
      skill({
        id: "fe-test",
        name: "组件 / E2E 测试",
        aliases: ["jest", "vitest", "cypress", "playwright", "testing-library"],
        level: "nice",
        category: "tool",
        jdPattern: "外企与部分国内中大厂 JD 会写单测/E2E；大量国内中小团队仍为加分。",
        learnHint: "给核心表单与关键路径补测试。",
        deliverable: "CI 中可跑的测试与说明。",
      }),
    ],
    projectTemplates: [
      {
        title: "完整中后台或内容型 SPA",
        detail:
          "含登录、权限、列表筛选、表单校验与错误态。用 TypeScript，并有可讲的状态设计。",
        evidence: "在线 Demo + 仓库 + 组件划分说明。",
        months: [2, 3],
      },
      {
        title: "性能优化或组件库切片",
        detail:
          "做一个设计令牌一致的小组件库，或对重页面做分包/虚拟列表优化。",
        evidence: "文档站点或性能对比数据。",
        months: [1, 2],
      },
    ],
    interviewFocus: [
      "React/Vue 渲染与状态",
      "浏览器网络与性能",
      "工程化取舍（为什么这样配）",
    ],
  },
  {
    id: "fullstack",
    name: "全栈开发工程师",
    nameEn: "Full-Stack Engineer",
    tagline: "能独立闭环一个小产品",
    summary:
      "创业团队、工具产品和部分中小企业 JD 常用「全栈」：前端能上线页面，后端能落库鉴权，并能自己部署。深度通常不如单端专家，但闭环能力是核心。",
    typicalTitles: {
      junior: "初级全栈 / 全栈开发（1–3 年）",
      mid: "全栈工程师（3–5 年）",
      senior: "高级全栈 / 技术负责人（5 年+）",
    },
    yearBands: { junior: [0, 2], mid: [3, 5], senior: [5, 15] },
    educationNote: "学历门槛与前后端类似；作品是否「能打开、能注册、能完成主流程」更关键。",
    sources: [
      "国内招聘平台对「全栈 / Node 全栈 / 独立开发」岗位的职责描述",
      "LinkedIn Full Stack JD 中前端框架 + 后端 API + 云部署的组合",
      "独立开发者与小型产品团队对「一人闭环」的通行要求",
    ],
    softSkills: ["产品感（知道先做哪条主路径）", "自我管理", "文档与演示"],
    skills: [
      skill({
        id: "fs-fe",
        name: "一门前端框架（React / Vue）",
        aliases: ["react", "vue", "next", "nextjs", "nuxt"],
        level: "must",
        category: "framework",
        jdPattern: "全栈 JD 通常要求能独立做管理端或用户端，而不是只调后端。",
        learnHint: "做出登录后的主路径页面，含错误与空态。",
        deliverable: "可演示的前端主流程。",
      }),
      skill({
        id: "fs-be",
        name: "一门后端栈（Node / Java / Python / Go）",
        aliases: ["node", "nodejs", "express", "nestjs", "java", "spring", "python", "fastapi", "go", "gin"],
        level: "must",
        category: "language",
        jdPattern: "全栈 JD 会写清后端语言；「只会前端 + BaaS」在国内社招里常被标成偏前端。",
        learnHint: "自己实现鉴权、CRUD 与权限，而不是完全依赖第三方后台。",
        deliverable: "带鉴权的 API 与数据模型。",
      }),
      skill({
        id: "fs-db",
        name: "数据库（SQL 或实用 NoSQL）",
        aliases: ["mysql", "postgresql", "postgres", "mongodb", "sqlite", "prisma", "sql"],
        level: "must",
        category: "infra",
        jdPattern: "全栈岗位默认能设计表/集合并处理基本查询与备份意识。",
        learnHint: "为产品主实体建模，写清约束与索引。",
        deliverable: "schema 与示例数据。",
      }),
      skill({
        id: "fs-auth",
        name: "鉴权与安全基线",
        aliases: ["jwt", "oauth", "鉴权", "登录", "session"],
        level: "must",
        category: "domain",
        jdPattern: "能上线的全栈项目几乎都被要求处理登录态、权限与基本安全（XSS/CSRF 意识）。",
        learnHint: "实现登录注册、角色权限，并处理常见 Web 安全点。",
        deliverable: "权限矩阵 + 安全检查清单。",
      }),
      skill({
        id: "fs-deploy",
        name: "部署与环境（Docker / 云主机 / 平台托管）",
        aliases: ["docker", "nginx", "vercel", "部署", "ci", "linux"],
        level: "should",
        category: "infra",
        jdPattern: "全栈 JD 很看重「能发布」；只有本地能跑在面试里说服力有限。",
        learnHint: "把应用部署到可访问环境，配置域名或至少公网 Demo。",
        deliverable: "在线地址 + 部署文档。",
      }),
      skill({
        id: "fs-ts",
        name: "TypeScript 或等价类型约束",
        aliases: ["typescript", "ts"],
        level: "should",
        category: "language",
        jdPattern: "Node/React 全栈 JD 普遍写 TypeScript，用于降低前后端契约漂移。",
        learnHint: "前后端共享类型或至少 API 类型生成。",
        deliverable: "类型化的 API 客户端。",
      }),
    ],
    projectTemplates: [
      {
        title: "可注册使用的小产品",
        detail:
          "例如个人知识库、约课、轻量 CRM。必须有真实用户主路径：注册、核心动作、数据持久化、部署。",
        evidence: "线上 Demo + 架构与取舍说明（为何不选某方案）。",
        months: [2, 4],
      },
    ],
    interviewFocus: [
      "如何独立排期并砍范围",
      "前后端契约与鉴权",
      "部署与故障时你怎么处理",
    ],
  },
  {
    id: "data-eng",
    name: "数据工程师",
    nameEn: "Data Engineer",
    tagline: "数仓、调度与可信数据",
    summary:
      "与数据分析/算法不同：核心是把业务数据稳定、可重复地变成表与管道。JD 高频词是 SQL、数仓建模、Spark/Flink、调度与数据质量。",
    typicalTitles: {
      junior: "初级数据开发 / 数仓开发（1–3 年）",
      mid: "数据工程师（3–5 年）",
      senior: "高级数据工程师 / 数据平台（5 年+）",
    },
    yearBands: { junior: [0, 2], mid: [3, 5], senior: [5, 15] },
    educationNote: "本科常见；统计/计算机/软件均可。算法岗学历门槛通常高于数据工程。",
    sources: [
      "国内「数据开发 / 数仓 / 大数据开发」JD（BOSS、拉勾、猎聘）对 SQL + Spark/Hive + 调度的写法",
      "LinkedIn Data Engineer JD 中管道、云数仓与数据质量职责",
      "数仓建模与调度领域的通行工程实践（维度建模、回补、幂等）",
    ],
    softSkills: ["和业务对指标口径", "对数据延迟与质量负责", "文档化表含义"],
    skills: [
      skill({
        id: "de-sql",
        name: "进阶 SQL",
        aliases: ["sql", "mysql", "postgresql", "hive", "clickhouse"],
        level: "must",
        category: "language",
        jdPattern: "数据岗 JD 把 SQL 当第一筛选器，窗口函数、多表与性能是面试标配。",
        learnHint: "系统练习窗口函数、去重、缓慢变化维与倾斜问题。",
        deliverable: "一套带注释的分析/数仓 SQL 练习与结论。",
      }),
      skill({
        id: "de-model",
        name: "数仓建模与分层",
        aliases: ["数仓", "维度建模", "ods", "dwd", "dws", "ads"],
        level: "must",
        category: "domain",
        jdPattern: "国内数仓开发 JD 普遍写分层（ODS/DWD/DWS）与维度建模，而不是只要会导数据。",
        learnHint: "选一个业务主题做分层设计和口径说明。",
        deliverable: "主题域模型图 + 口径文档。",
      }),
      skill({
        id: "de-engine",
        name: "批/流计算引擎（Spark 或 Flink）",
        aliases: ["spark", "flink", "hadoop", "mapreduce"],
        level: "must",
        category: "framework",
        jdPattern: "中大型数据 JD 几乎必写 Spark 和/或 Flink；只写 Pandas 通常对不上「数据工程」 Titling。",
        learnHint: "用 Spark 或 Flink 完成一次清洗与汇总作业。",
        deliverable: "可重跑的作业与资源/分区说明。",
      }),
      skill({
        id: "de-py",
        name: "Python 或 Scala/Java（作业与工具）",
        aliases: ["python", "scala", "java"],
        level: "must",
        category: "language",
        jdPattern: "管道脚本、UDF 与调度配套代码在 JD 中非常常见。",
        learnHint: "用 Python 写可参数化的作业入口与基础校验。",
        deliverable: "带配置与日志的作业模板。",
      }),
      skill({
        id: "de-orch",
        name: "调度与编排（Airflow 等）",
        aliases: ["airflow", "azkaban", "dolphinscheduler", "调度"],
        level: "should",
        category: "tool",
        jdPattern: "社招数据岗常写任务依赖、补数据、失败重跑；调度工具是具体载体。",
        learnHint: "编排一个有依赖与重试的 DAG。",
        deliverable: "DAG 代码 + 失败重跑说明。",
      }),
      skill({
        id: "de-dq",
        name: "数据质量与口径治理",
        aliases: ["数据质量", "dq", "great expectations", "数据治理"],
        level: "should",
        category: "domain",
        jdPattern: "较成熟团队 JD 会写质量规则、监控与对账，避免「表在但不可信」。",
        learnHint: "为关键表加唯一性/空值/波动检查。",
        deliverable: "质量规则清单与一次告警复盘。",
      }),
      skill({
        id: "de-kafka",
        name: "日志/消息接入（Kafka 等）",
        aliases: ["kafka", "binlog", "cdc", "flink cdc"],
        level: "nice",
        category: "infra",
        jdPattern: "实时数仓与用户行为管道 JD 常写 Kafka/CDC，离线岗则为加分。",
        learnHint: "理解至少一条从日志到表的链路。",
        deliverable: "链路示意图 + 延迟/一致性说明。",
      }),
    ],
    projectTemplates: [
      {
        title: "一个主题域的小型数仓",
        detail:
          "用公开数据集或脱敏业务数据，完成分层、调度与 3–5 张可分析表，并写清口径。",
        evidence: "模型文档 + 可重跑作业 + 样例看板或 SQL。",
        months: [2, 4],
      },
    ],
    interviewFocus: [
      "SQL 与数据倾斜",
      "分层与口径如何对齐业务",
      "作业失败与补数策略",
    ],
  },
  {
    id: "ml",
    name: "机器学习 / 算法工程师",
    nameEn: "ML / Applied Scientist",
    tagline: "建模、评测与可复现实验",
    summary:
      "国内「算法工程师」覆盖推荐、CV、NLP、搜索等。JD 对数学、编程与业务指标同时要，学历门槛通常高于纯工程岗。本画像对应应用算法，而非纯研究科学家。",
    typicalTitles: {
      junior: "算法实习生 / 初级算法（0–2 年）",
      mid: "算法工程师（2–5 年）",
      senior: "高级算法 / 算法专家（5 年+）",
    },
    yearBands: { junior: [0, 2], mid: [2, 5], senior: [5, 15] },
    educationNote:
      "国内一线算法 JD 大量写「硕士优先」或硬性硕士；本科需用竞赛、论文或可复现项目明显补强。",
    sources: [
      "国内算法/机器学习社招 JD（BOSS、猎聘、拉勾）对 Python + PyTorch + 机器学习基础的写法",
      "LinkedIn Machine Learning Engineer JD 对评测、部署与实验记录的要求",
      "课程与开源社区对可复现实验（数据、指标、消融）的通行标准",
    ],
    softSkills: ["把业务目标翻译成指标", "实验记录诚实", "能向工程同事讲清边界"],
    skills: [
      skill({
        id: "ml-py",
        name: "Python 与科学计算",
        aliases: ["python", "numpy", "pandas", "jupyter"],
        level: "must",
        category: "language",
        jdPattern: "算法 JD 默认 Python 熟练，并能处理表格/特征而不是只会调包。",
        learnHint: "用 Pandas/NumPy 完成特征与评测脚本，避免全程手点 Notebook。",
        deliverable: "可重复运行的训练/评测脚本。",
      }),
      skill({
        id: "ml-basic",
        name: "机器学习基础（监督/正则/过拟合）",
        aliases: ["机器学习", "machine learning", "xgboost", "lightgbm", "sklearn"],
        level: "must",
        category: "domain",
        jdPattern: "即使做深度学习的 JD 也会考偏差方差、特征与经典模型，用于判断是否只会套 Transformer。",
        learnHint: "手写或精读逻辑回归/树模型，并完成一个表格预测任务。",
        deliverable: "含基线对比的实验报告。",
      }),
      skill({
        id: "ml-dl",
        name: "深度学习框架（PyTorch 优先）",
        aliases: ["pytorch", "tensorflow", "keras", "deep learning"],
        level: "must",
        category: "framework",
        jdPattern: "国内算法 JD 近数年以 PyTorch 为主，TensorFlow 仍见于部分团队。",
        learnHint: "独立完成一个小模型的训练、验证与推理脚本。",
        deliverable: "训练曲线、指标与可复现随机种子说明。",
      }),
      skill({
        id: "ml-math",
        name: "概率统计与线性代数基础",
        aliases: ["概率", "统计", "线性代数", "微积分"],
        level: "must",
        category: "domain",
        jdPattern: "算法面试仍普遍包含基础题；JD 常写「扎实的数学基础」。",
        learnHint: "按面试常见范围补齐，能解释你用过的损失与优化器。",
        deliverable: "一页「我用过的公式与假设」笔记。",
      }),
      skill({
        id: "ml-algo",
        name: "数据结构与算法（编程面试）",
        aliases: ["leetcode", "算法", "数据结构", "剑指"],
        level: "should",
        category: "domain",
        jdPattern: "一线互联网算法岗通常仍有编程面试轮，与建模轮并列。",
        learnHint: "按中等题量稳定输出，覆盖数组、树、图、动态规划。",
        deliverable: "分类题解（自己的语言，强调思路）。",
      }),
      skill({
        id: "ml-mlops",
        name: "评测、实验管理与基本部署",
        aliases: ["mlops", "mlflow", "评测", "推理", "onnx"],
        level: "should",
        category: "tool",
        jdPattern: "应用算法 JD 越来越写「能落地」：指标、监控、简单服务化。",
        learnHint: "把模型封成可调用服务，并固定评测集。",
        deliverable: "评测集 + 推理 API + 实验记录表。",
      }),
    ],
    projectTemplates: [
      {
        title: "带强基线的应用建模项目",
        detail:
          "选可获取的数据（推荐、分类、检测之一），先做强传统基线，再上深度学习，写清指标与失败案例。",
        evidence: "可复现仓库 + 实验表 + 错误分析，而不是只有准确率截图。",
        months: [3, 5],
      },
    ],
    interviewFocus: [
      "指标是否匹配业务",
      "过拟合与数据泄漏",
      "你相对基线到底提升了什么",
    ],
  },
  {
    id: "llm-app",
    name: "LLM 应用工程师",
    nameEn: "LLM Application Engineer",
    tagline: "把大模型做成可运维的产品能力",
    summary:
      "2024 年后大量出现的岗位，名称含「大模型应用 / AIGC 应用 / LLM 工程师」。与算法岗不同：更强调 RAG、评测、工程化与产品效果，而不是从零训练基座。",
    typicalTitles: {
      junior: "大模型应用开发（0–2 年相关）",
      mid: "LLM 应用工程师（2–4 年软件 + 相关项目）",
      senior: "高级 LLM 应用 / AI 应用架构（4 年+ 工程）",
    },
    yearBands: { junior: [0, 2], mid: [2, 5], senior: [5, 15] },
    educationNote:
      "多数 JD 接受本科软件背景；有算法学历加分，但可上线的 RAG/工作流项目往往更决定面试。",
    sources: [
      "国内招聘平台「大模型应用 / AIGC 开发 / LLM 工程师」JD 对 RAG、Prompt、向量库与后端工程的组合",
      "LinkedIn 上 LLM / Generative AI Engineer JD 对评测、护栏与生产化的写法",
      "开源 RAG 与应用框架文档中的通行组件（检索、重排、引用、追踪）",
    ],
    softSkills: ["能定义「什么叫回答正确」", "对幻觉与安全边界诚实", "和产品一起砍范围"],
    skills: [
      skill({
        id: "llm-py",
        name: "Python 后端工程能力",
        aliases: ["python", "fastapi", "flask", "django"],
        level: "must",
        category: "language",
        jdPattern:
          "LLM 应用 JD 绝大多数按软件工程师招，要求能写服务、日志、限流，而不是只会 Chat UI。",
        learnHint: "用 FastAPI（或同等）把模型调用做成带超时、重试、日志的服务。",
        deliverable: "可观测的模型调用 API。",
      }),
      skill({
        id: "llm-api",
        name: "主流模型 API 与上下文管理",
        aliases: ["openai", "gpt", "claude", "qwen", "通义", "文心", "llm", "prompt"],
        level: "must",
        category: "domain",
        jdPattern: "JD 常写熟悉至少一家模型 API、Prompt 设计与 token/上下文限制。",
        learnHint: "系统记录不同提示与参数对同一评测集的效果，避免只靠感觉调。",
        deliverable: "提示词版本表 + 效果对比。",
      }),
      skill({
        id: "llm-rag",
        name: "RAG（切片、检索、引用）",
        aliases: ["rag", "检索增强", "embedding", "向量", "faiss", "milvus", "chroma"],
        level: "must",
        category: "domain",
        jdPattern: "企业知识问答类 JD 几乎必写 RAG / 向量库；只做「把 PDF 丢进对话」通常不够。",
        learnHint: "实现切片、元数据、引用出处，并分析失败问答。",
        deliverable: "带引用的知识问答 Demo + 失败案例集。",
      }),
      skill({
        id: "llm-eval",
        name: "应用评测（正确性 / 拒答 / 延迟）",
        aliases: ["评测", "eval", "ragas", "golden"],
        level: "should",
        category: "domain",
        jdPattern: "较认真的团队 JD 与面试会问你如何知道「变好了」；只说「感觉更聪明」很难过关。",
        learnHint: "做 30–50 条黄金集，覆盖正确、拒答、过期知识。",
        deliverable: "黄金集 + 每次改动的对比表。",
      }),
      skill({
        id: "llm-fw",
        name: "编排框架或等价自研（LangChain 等）",
        aliases: ["langchain", "llamaindex", "haystack", "dify", "编排"],
        level: "should",
        category: "framework",
        jdPattern: "JD 常点名 LangChain/LlamaIndex/Dify，但面试更看你是否理解检索与工具调用，而不是会堆组件。",
        learnHint: "用框架或自研完成一条可跟踪的调用链。",
        deliverable: "调用链日志（输入、检索、模型、输出）。",
      }),
      skill({
        id: "llm-prod",
        name: "缓存、限流、成本与安全护栏",
        aliases: ["限流", "缓存", "护栏", "content safety", "成本"],
        level: "should",
        category: "infra",
        jdPattern: "生产向 JD 会写成本、敏感信息、越狱与限流；演示型项目常缺这些而被认为偏玩具。",
        learnHint: "加上基础护栏、缓存重复问题和费用估算。",
        deliverable: "护栏策略 + 粗算成本表。",
      }),
    ],
    projectTemplates: [
      {
        title: "带评测的领域 RAG",
        detail:
          "选你熟悉的领域文档，做可引用问答，固定黄金集。强调失败分析，而不是模型品牌。",
        evidence: "仓库、评测表、引用示例、已知局限。",
        months: [2, 3],
      },
      {
        title: "工作流型 LLM 功能",
        detail:
          "例如工单分类 + 草稿回复，或简历要点抽取。要有结构化输出与人工确认节点。",
        evidence: "前后对比（人工耗时/错误类型）——用你自己的小样本，勿编造大规模统计。",
        months: [1, 2],
      },
    ],
    interviewFocus: [
      "RAG 失败模式（检索错 vs 生成错）",
      "如何评测而不是只 Demo",
      "成本、延迟与安全如何取舍",
    ],
  },
  {
    id: "agent",
    name: "Agent 开发工程师",
    nameEn: "Agent Engineer",
    tagline: "工具调用、状态机与失败恢复",
    summary:
      "比「会调 Chat API」更窄：JD 关注工具/函数调用、多步计划、记忆、权限与可观测。很多岗位从后端或 LLM 应用岗迁移而来，单独岗位名称仍在形成中。",
    typicalTitles: {
      junior: "Agent 应用开发（需有工程底子）",
      mid: "Agent 开发工程师",
      senior: "高级 Agent / 智能体平台工程师",
    },
    yearBands: { junior: [1, 3], mid: [3, 6], senior: [6, 15] },
    educationNote: "更看重软件工程与系统能力；纯提示词经验通常不足以支撑该岗位名称。",
    sources: [
      "国内「智能体开发 / Agent 工程师 / 应用算法（Agent）」JD 对工具调用、工作流与评测的描述",
      "全球招聘与开源 Agent 框架文档中对 tool use、memory、guardrail 的通行分解",
      "后端工程 JD 中与 Agent 重叠的部分：超时、重试、权限、审计日志",
    ],
    softSkills: ["把自主性限制在可审计范围", "对失败路径偏执", "跨工具调试"],
    skills: [
      skill({
        id: "ag-eng",
        name: "扎实的后端 / 全栈工程",
        aliases: ["python", "java", "go", "fastapi", "spring", "node"],
        level: "must",
        category: "language",
        jdPattern:
          "Agent JD 通常要求候选人先是工程师：能写服务、处理超时与权限。只做过聊天机器人前端的简历容易被筛。",
        learnHint: "先具备独立交付一个服务的能力，再叠加 Agent 循环。",
        deliverable: "可部署的后端服务（即使业务简单）。",
      }),
      skill({
        id: "ag-tool",
        name: "工具调用 / Function Calling",
        aliases: ["function calling", "tool use", "tools", "mcp", "插件"],
        level: "must",
        category: "domain",
        jdPattern: "真正的 Agent 岗会写「工具编排 / function calling / 插件」，而不是只写 Prompt。",
        learnHint: "设计 3–5 个真实工具（查询、写入、检索），处理参数校验与失败。",
        deliverable: "工具清单、JSON Schema 与失败用例。",
      }),
      skill({
        id: "ag-state",
        name: "状态、记忆与循环控制",
        aliases: ["memory", "state", "planner", "react", "多步"],
        level: "must",
        category: "domain",
        jdPattern: "JD 与技术分享中普遍把 Agent 看成带状态的循环，而不是单次补全。",
        learnHint: "实现 Thought-Action-Observation 或等价状态机，并限制最大步数。",
        deliverable: "可回放的轨迹日志。",
      }),
      skill({
        id: "ag-eval",
        name: "任务评测与回归",
        aliases: ["评测", "eval", "trajectory", "回归"],
        level: "should",
        category: "domain",
        jdPattern: "靠谱团队会关心任务成功率与回归，而不是单次惊艳 Demo。",
        learnHint: "固化 15–30 个任务脚本（成功/应拒绝/应澄清）。",
        deliverable: "任务集 + 成功率记录（小样本即可，勿虚报）。",
      }),
      skill({
        id: "ag-obs",
        name: "追踪、权限与护栏",
        aliases: ["tracing", "langsmith", "otel", "权限", "sandbox"],
        level: "should",
        category: "infra",
        jdPattern: "涉及写操作或浏览器/代码执行的 JD 会强调沙箱、审计与最小权限。",
        learnHint: "给危险工具加确认与沙箱，轨迹可追溯到每一步工具调用。",
        deliverable: "权限矩阵 + 轨迹查看方式。",
      }),
      skill({
        id: "ag-rag",
        name: "检索与上下文装配（常与 RAG 重叠）",
        aliases: ["rag", "检索", "embedding"],
        level: "should",
        category: "domain",
        jdPattern: "企业 Agent 很少凭空生成，JD 常同时写知识库/检索。",
        learnHint: "让 Agent 先检索再行动，并引用依据。",
        deliverable: "带检索步骤的轨迹示例。",
      }),
    ],
    projectTemplates: [
      {
        title: "受限域 Agent（工具 ≤ 6 个）",
        detail:
          "例如「查询内部 FAQ + 创建工单草稿」。必须有最大步数、拒绝策略、轨迹回放，避免做成无限聊天。",
        evidence: "轨迹、任务集、已知失败模式。",
        months: [2, 4],
      },
    ],
    interviewFocus: [
      "如何防止 Agent 胡乱调用写工具",
      "循环何时停止",
      "你如何证明改动没有变差",
    ],
  },
  {
    id: "devops",
    name: "DevOps / SRE 工程师",
    nameEn: "DevOps / SRE",
    tagline: "交付、稳定性与可恢复性",
    summary:
      "国内岗位名称含运维开发、DevOps、SRE、平台工程。JD 看 Linux、网络、CI/CD、容器与云，高级岗还看容量、事故复盘与 IaC。",
    typicalTitles: {
      junior: "运维 / 初级 DevOps（1–3 年）",
      mid: "DevOps / SRE（3–5 年）",
      senior: "高级 SRE / 稳定性专家（5 年+）",
    },
    yearBands: { junior: [0, 2], mid: [3, 5], senior: [5, 15] },
    educationNote: "本科常见；大量岗位接受大专，前提是有真实值班/事故/流水线经验。",
    sources: [
      "国内「运维开发 / DevOps / SRE」JD（BOSS、拉勾、猎聘）对 Linux、K8s、CI/CD、监控的清单",
      "LinkedIn SRE/DevOps JD 对 SLO、值班、IaC 的常见职责",
      "Google SRE 公开书籍与云厂商文档中的稳定性实践（作为方法论来源，非具体招聘承诺）",
    ],
    softSkills: ["事故时沟通清楚", "变更克制", "把重复劳动自动化"],
    skills: [
      skill({
        id: "do-linux",
        name: "Linux 与网络基础",
        aliases: ["linux", "tcp", "http", "dns", "nginx"],
        level: "must",
        category: "infra",
        jdPattern: "运维/SRE JD 把 Linux、网络排障当硬门槛，不会因为会云控制台而豁免。",
        learnHint: "练习进程、磁盘、网络排查与常见 Web 反向代理。",
        deliverable: "一份真实排障笔记（环境可以是自建实验）。",
      }),
      skill({
        id: "do-script",
        name: "脚本能力（Bash / Python）",
        aliases: ["bash", "shell", "python", "ansible"],
        level: "must",
        category: "language",
        jdPattern: "JD 普遍要求能写自动化脚本，而不是纯点图形界面。",
        learnHint: "把一项重复操作写成幂等脚本。",
        deliverable: "带参数校验的运维脚本 + 使用说明。",
      }),
      skill({
        id: "do-docker",
        name: "容器（Docker）",
        aliases: ["docker", "oci", "containerd"],
        level: "must",
        category: "infra",
        jdPattern: "当代 DevOps JD 的基线：镜像、层、资源限制、安全基础。",
        learnHint: "多阶段构建、非 root、健康检查。",
        deliverable: "规范 Dockerfile 与镜像扫描记录（可用开源工具）。",
      }),
      skill({
        id: "do-ci",
        name: "CI/CD",
        aliases: ["ci", "cd", "jenkins", "gitlab ci", "github actions", "流水线"],
        level: "must",
        category: "tool",
        jdPattern: "几乎所有 DevOps JD 写流水线；内容包括构建、测试门禁、分环境发布。",
        learnHint: "为应用加上构建-测试-部署流水线，区分环境。",
        deliverable: "流水线配置 + 回滚说明。",
      }),
      skill({
        id: "do-k8s",
        name: "Kubernetes",
        aliases: ["kubernetes", "k8s", "helm"],
        level: "should",
        category: "infra",
        jdPattern: "中大厂与云原生团队 JD 常把 K8s 当硬性要求；传统运维岗可能仍以主机为主。",
        learnHint: "部署无状态服务，理解 Probe、资源、滚动发布。",
        deliverable: "清单/Helm 与故障演练记录。",
      }),
      skill({
        id: "do-obs",
        name: "监控告警与日志",
        aliases: ["prometheus", "grafana", "alertmanager", "elk", "loki", "监控"],
        level: "should",
        category: "infra",
        jdPattern: "SRE 向 JD 强调指标、告警噪音治理与值班；只有机器在线不算。",
        learnHint: "为服务定义黄金指标与告警，并做一次误报治理。",
        deliverable: "仪表盘 + 告警列表 + 值班备忘。",
      }),
      skill({
        id: "do-iac",
        name: "基础设施即代码",
        aliases: ["terraform", "ansible", "pulumi", "iac"],
        level: "nice",
        category: "tool",
        jdPattern: "云团队与外企 JD 常见 Terraform/Ansible；部分国内团队仍为加分。",
        learnHint: "用 IaC 管理一小块可销毁重建的环境。",
        deliverable: "IaC 仓库 + 销毁/重建步骤。",
      }),
    ],
    projectTemplates: [
      {
        title: "一条完整交付链路",
        detail:
          "应用 → 镜像 → 流水线 → 运行环境 → 监控告警。可用开源应用，重点是你能讲清失败与回滚。",
        evidence: "仓库、流水线截图/配置、一次演练记录。",
        months: [2, 3],
      },
    ],
    interviewFocus: [
      "一次故障的时间线",
      "发布如何回滚",
      "告警是否可行动",
    ],
  },
  {
    id: "qa",
    name: "测试开发 / QA 工程师",
    nameEn: "QA / SDET",
    tagline: "风险发现与质量反馈闭环",
    summary:
      "国内岗位从功能测试延伸到测试开发（SDET）。JD 对自动化、接口测试、CI 集成的要求逐年上升；纯手工点测在一线城市机会更窄。",
    typicalTitles: {
      junior: "功能测试 / 初级测试（0–2 年）",
      mid: "测试开发 / QA（2–5 年）",
      senior: "高级测试开发 / 质量专家（5 年+）",
    },
    yearBands: { junior: [0, 2], mid: [2, 5], senior: [5, 15] },
    educationNote: "本科常见；测试开发对编程要求接近初级开发，功能测试对业务细心要求更高。",
    sources: [
      "国内「测试开发 / 自动化测试 / QA」JD 对 Python/Java + 接口自动化 + CI 的写法",
      "LinkedIn SDET/QA Engineer JD 对测试金字塔与质量度量的描述",
      "行业对接口、契约、回归门禁的通行实践",
    ],
    softSkills: ["会提问需求漏洞", "缺陷描述可复现", "在进度压力下仍标清风险"],
    skills: [
      skill({
        id: "qa-theory",
        name: "测试设计（等价类、边界、场景）",
        aliases: ["测试用例", "测试设计", "等价类", "边界值"],
        level: "must",
        category: "domain",
        jdPattern: "所有测试 JD 的底线；面试常要求当场设计用例。",
        learnHint: "对一个真实功能写出分层用例，并标优先级。",
        deliverable: "用例集 + 风险列表。",
      }),
      skill({
        id: "qa-lang",
        name: "一门编程语言（Python / Java / JS）",
        aliases: ["python", "java", "javascript", "typescript"],
        level: "must",
        category: "language",
        jdPattern: "测试开发 JD 必写语言；纯功能测试岗可能弱化，但一线城市越来越要求能写脚本。",
        learnHint: "能独立写脚本处理数据和调用接口。",
        deliverable: "小型测试工具或脚本库。",
      }),
      skill({
        id: "qa-api",
        name: "接口测试",
        aliases: ["接口测试", "postman", "rest assured", "pytest", "httpie"],
        level: "must",
        category: "tool",
        jdPattern: "当前国内 QA JD 把接口自动化当作中级门槛，高于纯 UI 录制。",
        learnHint: "对一组 API 做自动化，含断言、数据隔离与报告。",
        deliverable: "可在 CI 跑的接口套件。",
      }),
      skill({
        id: "qa-auto",
        name: "UI 或端到端自动化（按栈选择）",
        aliases: ["selenium", "playwright", "cypress", "appium"],
        level: "should",
        category: "tool",
        jdPattern: "C 端产品 JD 常写 UI 自动化；强后端团队可能更看接口与契约。",
        learnHint: "只覆盖主路径，避免脆弱大而全 UI 套件。",
        deliverable: "主路径 E2E + 维护说明。",
      }),
      skill({
        id: "qa-ci",
        name: "CI 门禁与质量反馈",
        aliases: ["jenkins", "gitlab ci", "github actions", "ci"],
        level: "should",
        category: "tool",
        jdPattern: "测试开发 JD 强调把自动化接入流水线，而不是只在本地点绿。",
        learnHint: "让失败测试能定位到提交，并控制执行时间。",
        deliverable: "门禁配置 + 失败处理约定。",
      }),
      skill({
        id: "qa-perf",
        name: "性能 / 专项测试认知",
        aliases: ["jmeter", "locust", "性能测试", "压测"],
        level: "nice",
        category: "domain",
        jdPattern: "部分岗位单列性能测试；通用 QA 则为加分。",
        learnHint: "做一次小规模压测，讲清指标与瓶颈，避免空报「支持高并发」。",
        deliverable: "压测方案与结果边界。",
      }),
    ],
    projectTemplates: [
      {
        title: "对开源或自建服务的质量套件",
        detail:
          "接口自动化 + 主路径 E2E + CI。写清覆盖了什么、故意不覆盖什么。",
        evidence: "仓库、CI 徽章/日志、缺陷样例报告。",
        months: [2, 3],
      },
    ],
    interviewFocus: [
      "如何设计用例与优先级",
      "自动化的维护成本",
      "怎样向开发报告缺陷",
    ],
  },
  {
    id: "tech-pm",
    name: "产品经理 / 技术 PM",
    nameEn: "Product Manager (Technical)",
    tagline: "问题定义、取舍与落地推进",
    summary:
      "技术向 PM（B 端、平台、开发者产品、AI 产品）JD 要求能读懂架构取舍、写清需求与验收，而不是只会画原型。纯增长/C 端运营向 PM 不在本画像中心。",
    typicalTitles: {
      junior: "产品助理 / 初级产品（0–2 年）",
      mid: "产品经理 / 技术 PM（2–5 年）",
      senior: "高级产品 / 产品负责人（5 年+）",
    },
    yearBands: { junior: [0, 2], mid: [2, 5], senior: [5, 15] },
    educationNote:
      "专业不限但理工或计算机常见于技术 PM；转岗者需用作品（需求文档、上线复盘）证明。",
    sources: [
      "国内「产品经理 / 技术产品 / B 端产品」JD 对需求、原型、数据分析、项目推进的职责描述",
      "LinkedIn Technical Product Manager JD 对路线图、利益相关方与技术约束的写法",
      "行业对 PRD、验收标准与上线复盘的通行文档结构",
    ],
    softSkills: ["主持对齐会议", "在资源不够时做减法", "把技术语言翻译给非技术同事"],
    skills: [
      skill({
        id: "pm-req",
        name: "需求抽象与验收标准",
        aliases: ["prd", "需求", "用户故事", "验收"],
        level: "must",
        category: "domain",
        jdPattern: "所有 PM JD 的核心：能写清问题、方案、范围外与验收，而不是只有功能清单。",
        learnHint: "完整写一份 PRD：问题、用户、方案、非目标、验收、风险。",
        deliverable: "1 份可被开发估时的 PRD。",
      }),
      skill({
        id: "pm-tech",
        name: "足够的技术理解（API、数据、约束）",
        aliases: ["api", "架构", "系统", "数据库", "技术"],
        level: "must",
        category: "domain",
        jdPattern: "技术 PM JD 明确要求能和研发讨论接口、性能与排期，而不是把所有细节甩给开发。",
        learnHint: "读懂并画出你目标领域的系统草图（组件、数据、关键路径）。",
        deliverable: "一页架构理解图 + 技术风险列表。",
      }),
      skill({
        id: "pm-data",
        name: "数据分析与指标",
        aliases: ["sql", "数据分析", "指标", "漏斗", "ab"],
        level: "should",
        category: "tool",
        jdPattern: "中级以上 PM JD 普遍写数据分析；SQL 在 B 端/平台岗很常见。",
        learnHint: "为功能定义北向指标与护栏指标，并用 SQL 或表格算出基线。",
        deliverable: "指标字典 + 一次复盘（可用小样本）。",
      }),
      skill({
        id: "pm-proj",
        name: "项目推进与沟通",
        aliases: ["项目管理", "jira", "迭代", "roadmap"],
        level: "must",
        category: "soft",
        jdPattern: "JD 职责部分通常一半是推进：排期、依赖、风险升级。",
        learnHint: "用公开或模拟项目练习迭代计划与风险登记。",
        deliverable: "路线图 + 风险表。",
      }),
      skill({
        id: "pm-ux",
        name: "原型与交互说明",
        aliases: ["figma", "原型", "axure", "交互"],
        level: "should",
        category: "tool",
        jdPattern: "C 端与部分 B 端 JD 写 Figma/原型；平台 PM 可能用流程图代替高保真。",
        learnHint: "把主路径做成可评审原型，标注异常态。",
        deliverable: "原型链接或截图 + 异常态说明。",
      }),
      skill({
        id: "pm-industry",
        name: "领域知识（按目标行业）",
        aliases: ["领域", "业务", "行业"],
        level: "nice",
        category: "domain",
        jdPattern: "金融、电商、产业互联网 JD 常把领域经验列为加分或硬性。",
        learnHint: "系统研究目标领域的对象模型与合规约束。",
        deliverable: "领域名词表 + 竞品结构笔记（基于公开信息）。",
      }),
    ],
    projectTemplates: [
      {
        title: "一个完整产品切片作品集",
        detail:
          "选题可以是改进开源工具或设想 B 端模块：研究、PRD、原型、指标、假想排期与复盘。标注哪些是假设。",
        evidence: "文档站点或 PDF 作品集，避免空泛愿景页。",
        months: [2, 3],
      },
    ],
    interviewFocus: [
      "你如何做减法",
      "和研发发生分歧时怎样处理",
      "用什么指标判断做成了",
    ],
  },
  {
    id: "mobile",
    name: "移动端开发工程师",
    nameEn: "Mobile Engineer",
    tagline: "Android / iOS / 跨端的客户端质量",
    summary:
      "JD 按 Android、iOS 或 Flutter/React Native 分栈。除语言外，稳定性、性能、包体积与发布节奏是中高级门槛。",
    typicalTitles: {
      junior: "初级 Android / iOS（0–2 年）",
      mid: "移动端开发（2–5 年）",
      senior: "高级移动端 / 端架构（5 年+）",
    },
    yearBands: { junior: [0, 2], mid: [2, 5], senior: [5, 15] },
    educationNote: "本科常见；跨端岗位有时接受前端转岗，但需要补齐原生生命周期与性能。",
    sources: [
      "国内 Android/iOS/Flutter JD 对语言、组件化、性能与发布的要求",
      "LinkedIn Mobile Engineer JD 对商店发布、崩溃率、离线同步的描述",
      "平台官方文档（Android / Apple / Flutter）中的工程基线",
    ],
    softSkills: ["对卡顿和崩溃敏感", "能与设计对齐适配", "关注发版风险"],
    skills: [
      skill({
        id: "mo-native",
        name: "原生或主流跨端栈（Kotlin/Java、Swift 或 Flutter/RN）",
        aliases: ["android", "kotlin", "java", "swift", "ios", "flutter", "react native", "rn"],
        level: "must",
        category: "language",
        jdPattern: "移动端 JD 按栈拆分，很少接受「只写过 WebView 套壳」作为同级经验。",
        learnHint: "用目标栈完成列表、详情、本地存储与网络层。",
        deliverable: "可安装的 App 或稳定模拟器 Demo。",
      }),
      skill({
        id: "mo-life",
        name: "生命周期、导航与状态恢复",
        aliases: ["lifecycle", "activity", "fragment", "swiftui", "navigation"],
        level: "must",
        category: "domain",
        jdPattern: "面试和 JD 都默认你理解前后台、旋转/进程杀死、深链。",
        learnHint: "专门处理后台杀死与深链恢复。",
        deliverable: "状态恢复说明与复现步骤。",
      }),
      skill({
        id: "mo-net",
        name: "网络、存储与数据同步",
        aliases: ["okhttp", "retrofit", "room", "coredata", "sqlite", "graphql"],
        level: "must",
        category: "infra",
        jdPattern: "客户端 JD 强调弱网、缓存与本地数据库，而不只是会调一个 JSON 接口。",
        learnHint: "实现离线缓存或重试，明确同步冲突策略。",
        deliverable: "弱网策略说明 + 实现。",
      }),
      skill({
        id: "mo-quality",
        name: "稳定性与性能（崩溃、卡顿、包体积）",
        aliases: ["crash", "anr", "leakcanary", "性能", "包体积"],
        level: "should",
        category: "domain",
        jdPattern: "中高级 JD 常写崩溃率、ANR、启动时间；初级岗为加分。",
        learnHint: "接入崩溃收集（可用开源），做一次启动或列表性能优化。",
        deliverable: "优化前后对比与复现环境。",
      }),
      skill({
        id: "mo-ci",
        name: "构建与发版",
        aliases: ["gradle", "fastlane", "ci", "签名", "testflight"],
        level: "should",
        category: "tool",
        jdPattern: "团队岗要求理解签名、多渠道/多 scheme、商店审核节奏。",
        learnHint: "把构建放到 CI，写清发版检查清单。",
        deliverable: "CI 配置 + 发版清单。",
      }),
    ],
    projectTemplates: [
      {
        title: "完整客户端小应用",
        detail:
          "含列表、详情、登录或本地账号、离线或缓存、错误态。上架非必须，但需可安装演示。",
        evidence: "APK/TestFlight/录像 + 架构说明。",
        months: [2, 4],
      },
    ],
    interviewFocus: [
      "生命周期与内存",
      "弱网与同步",
      "你如何定位崩溃/卡顿",
    ],
  },
  {
    id: "security",
    name: "安全工程师（应用 / 安全开发）",
    nameEn: "Security Engineer",
    tagline: "威胁、漏洞治理与安全开发",
    summary:
      "本画像对应应用安全、安全开发与偏工程的安服，而不是纯售前。JD 常见 OWASP、漏洞生命周期、SDL、渗透或代码审计之一。",
    typicalTitles: {
      junior: "安全实习生 / 初级安全工程师",
      mid: "应用安全 / 安全开发（2–5 年）",
      senior: "高级安全工程师（5 年+）",
    },
    yearBands: { junior: [0, 2], mid: [2, 5], senior: [5, 15] },
    educationNote: "计算机/信息安全本科常见；证书（如 CISSP 等）在部分甲方加分，但通常替代不了漏洞案例。",
    sources: [
      "国内「安全工程师 / 安全开发 / 应用安全」JD 对 Web 安全、渗透、SDL 的职责描述",
      "OWASP Top 10 等公开标准在全球安全 JD 中的引用方式",
      "等保与漏洞运营在国内甲方 JD 中的常见表述（作为合规背景，非具体机构背书）",
    ],
    softSkills: ["漏洞报告对开发可读", "不夸大风险等级", "能推动修复闭环"],
    skills: [
      skill({
        id: "sec-web",
        name: "Web 安全基础（OWASP 类问题）",
        aliases: ["owasp", "xss", "sql injection", "csrf", "ssrf", "web安全"],
        level: "must",
        category: "domain",
        jdPattern: "应用安全 JD 几乎都写 Web 漏洞类型；这是与开发沟通的共同语言。",
        learnHint: "在合法靶场理解常见漏洞原理与修复，而不是收集未授权目标。",
        deliverable: "合法靶场笔记：原理、复现、修复建议。",
      }),
      skill({
        id: "sec-lang",
        name: "一门开发语言（能读代码）",
        aliases: ["python", "java", "go", "javascript", "php"],
        level: "must",
        category: "language",
        jdPattern: "安全开发与代码审计岗要求能读业务代码；只会扫描器的简历在工程安全岗偏弱。",
        learnHint: "能从头读一个 Web 项目并标出信任边界。",
        deliverable: "对开源项目的审计备忘（仅公开项目）。",
      }),
      skill({
        id: "sec-linux",
        name: "Linux 与网络基础",
        aliases: ["linux", "tcp", "http", "wireshark"],
        level: "must",
        category: "infra",
        jdPattern: "安全 JD 默认会抓包、看日志、理解部署形态。",
        learnHint: "练习从日志与流量理解一次请求的信任链。",
        deliverable: "一次合法环境的流量分析笔记。",
      }),
      skill({
        id: "sec-sdl",
        name: "漏洞运营或 SDL 流程",
        aliases: ["sdl", "漏洞", "工单", "威胁建模"],
        level: "should",
        category: "domain",
        jdPattern: "甲方安全 JD 很看重工单闭环、评级与再验证，而不是只出扫描报告。",
        learnHint: "设计一个迷你漏洞生命周期（发现-评级-修复-复测）。",
        deliverable: "流程说明 + 模板。",
      }),
      skill({
        id: "sec-tool",
        name: "安全测试工具链（按方向）",
        aliases: ["burp", "nuclei", "semgrep", "codeql"],
        level: "should",
        category: "tool",
        jdPattern: "渗透向写 Burp 等，安全开发向写 SAST/依赖扫描。工具是手段。",
        learnHint: "选与目标方向匹配的工具，写清误报如何处理。",
        deliverable: "工具使用手册（含误报例子）。",
      }),
      skill({
        id: "sec-cloud",
        name: "云 / 容器安全认知",
        aliases: ["云安全", "k8s安全", "iam", "waf"],
        level: "nice",
        category: "infra",
        jdPattern: "上云团队 JD 常加 IAM、镜像、WAF；传统主机房团队可能较弱。",
        learnHint: "理解身份、密钥与网络隔离的基线错误。",
        deliverable: "一份云安全检查清单（基于官方公开最佳实践）。",
      }),
    ],
    projectTemplates: [
      {
        title: "公开项目的应用安全作品集",
        detail:
          "对开源 Web 应用做威胁建模 + 合法测试 + 修复建议。禁止扫描未授权系统。可附你实现的加固补丁。",
        evidence: "报告结构完整：范围、方法、发现、复现、修复、再验证。",
        months: [2, 3],
      },
    ],
    interviewFocus: [
      "你如何评级与沟通漏洞",
      "误报与漏报",
      "如何在业务进度下推动修复",
    ],
  },
];

export const ROLE_MAP = Object.fromEntries(ROLES.map((role) => [role.id, role]));

export function getRole(id: string): RoleProfile | undefined {
  return ROLE_MAP[id];
}
